# port
server:
  port: 9010

# About database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jj910712
  redis:
    host: 127.0.0.1
    database: 0    # redis数据库
    port: 6379
    password: redis
    timeout: 30000s
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8
        max-wait: 60000ms
        max-idle: 8
        min-idle: 0
  cache:
    type: redis


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jwt.entity
  global-config:
    db-config:
      id-type: auto

# log
logging:
  file:
    path: logs/sys.log
  level:
    com.jwt.dao: debug

